//Mock data for testing
const mockEmployees = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "1990-01-01",
    startDate: "2020-01-01",
    street: "1 rue de la paix",
    city: "Paris",
    state: "France",
    zipCode: "75000",
    department: "IT",
  },
  {
    id: 2,
    firstName: "Ilane",
    lastName: "Doe",
    dateOfBirth: "1990-01-01",
    startDate: "2020-01-01",
    street: "1 rue de la paix",
    city: "Paris",
    state: "France",
    zipCode: "75000",
    department: "IT",
  },
  {
    id: 3,
    firstName: "Johny",
    lastName: "Smith",
    dateOfBirth: "1990-01-01",
    startDate: "2020-01-01",
    street: "1 rue de la paix",
    city: "Paris",
    state: "France",
    zipCode: "75000",
    department: "IT",
  },
  {
    id: 4,
    firstName: "Alice",
    lastName: "Johnson",
    dateOfBirth: "1985-02-15",
    startDate: "2019-03-10",
    street: "123 Main Street",
    city: "New York",
    state: "USA",
    zipCode: "10001",
    department: "HR",
  },
  {
    id: 5,
    firstName: "Bob",
    lastName: "Williams",
    dateOfBirth: "1988-07-20",
    startDate: "2017-09-05",
    street: "456 Elm Street",
    city: "Los Angeles",
    state: "USA",
    zipCode: "90001",
    department: "Marketing",
  },
  {
    id: 6,
    firstName: "Emma",
    lastName: "Brown",
    dateOfBirth: "1992-12-05",
    startDate: "2018-10-15",
    street: "789 Oak Street",
    city: "Chicago",
    state: "USA",
    zipCode: "60001",
    department: "Finance",
  },
  {
    id: 7,
    firstName: "James",
    lastName: "Taylor",
    dateOfBirth: "1983-03-30",
    startDate: "2016-07-01",
    street: "101 Pine Street",
    city: "San Francisco",
    state: "USA",
    zipCode: "94101",
    department: "Sales",
  },
  {
    id: 8,
    firstName: "Olivia",
    lastName: "Davis",
    dateOfBirth: "1995-05-10",
    startDate: "2015-04-20",
    street: "222 Cedar Street",
    city: "Houston",
    state: "USA",
    zipCode: "77001",
    department: "Customer Support",
  },
  {
    id: 9,
    firstName: "Michael",
    lastName: "Johnson",
    dateOfBirth: "1980-09-25",
    startDate: "2014-12-10",
    street: "333 Birch Street",
    city: "Miami",
    state: "USA",
    zipCode: "33101",
    department: "Engineering",
  },
  {
    id: 10,
    firstName: "Sophia",
    lastName: "Martinez",
    dateOfBirth: "1991-11-12",
    startDate: "2013-02-28",
    street: "444 Maple Street",
    city: "Dallas",
    state: "USA",
    zipCode: "75201",
    department: "Product Development",
  },
  {
    id: 11,
    firstName: "David",
    lastName: "Brown",
    dateOfBirth: "1987-04-18",
    startDate: "2012-05-15",
    street: "555 Walnut Street",
    city: "Atlanta",
    state: "USA",
    zipCode: "30301",
    department: "Sales",
  },
  {
    id: 12,
    firstName: "Emily",
    lastName: "Smith",
    dateOfBirth: "1993-08-25",
    startDate: "2011-03-20",
    street: "666 Oak Avenue",
    city: "Seattle",
    state: "USA",
    zipCode: "98101",
    department: "Marketing",
  },
  {
    id: 13,
    firstName: "William",
    lastName: "Wilson",
    dateOfBirth: "1986-01-12",
    startDate: "2010-09-30",
    street: "777 Elm Avenue",
    city: "Boston",
    state: "USA",
    zipCode: "02201",
    department: "Finance",
  },
  {
    id: 14,
    firstName: "Ella",
    lastName: "Johnson",
    dateOfBirth: "1994-06-08",
    startDate: "2009-12-05",
    street: "888 Cedar Avenue",
    city: "Denver",
    state: "USA",
    zipCode: "80201",
    department: "Customer Support",
  },
  {
    id: 15,
    firstName: "Liam",
    lastName: "Thomas",
    dateOfBirth: "1989-03-05",
    startDate: "2008-06-10",
    street: "999 Birch Avenue",
    city: "Phoenix",
    state: "USA",
    zipCode: "85001",
    department: "Engineering",
  },
];

const headers = [
  { name: "First Name", data: "firstName" },
  { name: "Last Name", data: "lastName" },
  { name: "Start Date", data: "startDate" },
  { name: "Department", data: "department" },
  { name: "Date of Birth", data: "dateOfBirth" },
  { name: "Street", data: "street" },
  { name: "City", data: "city" },
  { name: "State", data: "state" },
  { name: "Zip Code", data: "zipCode" },
];

export { mockEmployees, headers };
